export const mockLibraryData = [
  // --- eBooks ---
  {
    id: 101,
    title: 'The Future of AI in Education',
    author: 'Dr. Evelyn Reed',
    module: 'AI & Machine Learning',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'An in-depth exploration of how artificial intelligence is set to revolutionize the educational landscape, from personalized learning paths to automated grading systems.',
    badge: 'AI',
    coverUrl: 'https://images.unsplash.com/photo-1599658880436-c61792e70672?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/',
  },
  {
    id: 102,
    title: 'Advanced JavaScript Frameworks',
    author: 'Ben Carter',
    module: 'Web Development',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'A comprehensive guide to modern JavaScript frameworks like React, Vue, and Svelte, focusing on performance and scalability.',
    badge: 'Programming',
    coverUrl: 'https://images.unsplash.com/photo-1526498460520-4c246339dccb?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/javascript-the-definitive-guide/9781491952016/',
  },
  {
    id: 103,
    title: 'Cybersecurity in the Cloud Era',
    author: 'Maria Rodriguez',
    module: 'Network Security',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'This book covers essential strategies for securing cloud infrastructure, data, and applications against modern cyber threats.',
    badge: 'Security',
    coverUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/cloud-security-and-privacy/9780596802769/',
  },
  {
    id: 104,
    title: 'Data Science for Business Leaders',
    author: 'Kenji Tanaka',
    module: 'Business Analytics',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'A practical guide for managers on how to leverage data science to make informed business decisions and drive growth.',
    badge: 'Business',
    coverUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/data-science-for/9781491952931/',
  },
  {
    id: 105,
    title: 'Sustainable Engineering Design',
    author: 'Dr. Aisha Khan',
    module: 'Civil Engineering',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'Principles and practices for designing engineering projects with a focus on environmental sustainability and long-term impact.',
    badge: 'Engineering',
    coverUrl: 'https://images.unsplash.com/photo-1487875961445-47a00398c267?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/sustainable-energy-without/9780954452933/',
  },
  {
    id: 106,
    title: 'The Psychology of User Experience',
    author: 'David Lee',
    module: 'Human-Computer Interaction',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'Understanding the cognitive and emotional factors that influence how users interact with digital products.',
    badge: 'UX/UI',
    coverUrl: 'https://images.unsplash.com/photo-1587440871875-191322ee64b0?q=80&w=2071&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/the-design-of-everyday/9780465050659/',
  },
  {
    id: 107,
    title: 'Global Economics: A Modern Perspective',
    author: 'Prof. Olivia Chen',
    module: 'Economics',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'An analysis of the interconnected global economy, covering trade, finance, and policy in the 21st century.',
    badge: 'Economics',
    coverUrl: 'https://images.unsplash.com/photo-1600489000024-cb48a70c6192?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/freakonomics/9780060731328/',
  },
  {
    id: 108,
    title: 'Mobile App Development with React Native',
    author: 'Emily White',
    module: 'Mobile Computing',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'A hands-on guide to building cross-platform mobile applications using React Native, from setup to deployment.',
    badge: 'Programming',
    coverUrl: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/react-native-cookbook/9781098102228/',
  },
  {
    id: 109,
    title: 'Introduction to Quantum Computing',
    author: 'Dr. Samuel Jones',
    module: 'Advanced Physics',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'A foundational text explaining the principles of quantum mechanics and their application in computing.',
    badge: 'Science',
    coverUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/quantum-computing-for/9781491932186/',
  },
  {
    id: 110,
    title: 'Digital Marketing Strategy',
    author: 'Chloe Green',
    module: 'Marketing',
    category: 'eBooks',
    type: 'eBook',
    availability: 'Online',
    description: 'Learn to create and implement effective digital marketing strategies across various channels, including social media, SEO, and email.',
    badge: 'Marketing',
    coverUrl: 'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop',
    url: 'https://www.oreilly.com/library/view/digital-marketing-all-in-one/9781119766656/',
  },

  // --- Lecturer Publications ---
  {
    id: 201,
    title: 'A Study on Reinforcement Learning for Autonomous Systems',
    author: 'Prof. Alan Turing',
    module: 'Faculty of Computing',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'Published in the International Journal of Robotics, this paper details a novel algorithm for improving decision-making in autonomous drones.',
    badge: 'Research Paper',
    coverUrl: 'https://images.unsplash.com/photo-1526253765975-dce1e5f6a6e4?q=80&w=2070&auto=format&fit=crop',
    url: 'https://arxiv.org/pdf/2106.04828.pdf',
  },
  {
    id: 202,
    title: 'The Impact of FinTech on Traditional Banking',
    author: 'Dr. Ada Lovelace',
    module: 'Faculty of Business',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'An analysis of how financial technology is disrupting the banking sector, presented at the Global Finance Conference.',
    badge: 'Conference Paper',
    coverUrl: 'https://images.unsplash.com/photo-1561414927-6d86591d0c4f?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.imf.org/en/Publications/fintech-notes/Issues/2019/06/25/The-Rise-of-Digital-Money-47021',
  },
  {
    id: 203,
    title: 'Graphene-Based Transistors for Next-Gen Electronics',
    author: 'Prof. Marie Curie',
    module: 'Faculty of Engineering',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'This article in "Nature Electronics" explores the potential of graphene to create faster, more efficient electronic components.',
    badge: 'Journal Article',
    coverUrl: 'https://images.unsplash.com/photo-1581092916346-3d1b4a7240dd?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.nature.com/articles/s41928-021-00581-3',
  },
  {
    id: 204,
    title: 'Cognitive Biases in Investment Decisions',
    author: 'Dr. Daniel Kahneman',
    module: 'Faculty of Humanities & Sciences',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'A book chapter detailing common psychological pitfalls that affect both amateur and professional investors.',
    badge: 'Book Chapter',
    coverUrl: 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?q=80&w=2089&auto=format&fit=crop',
    url: 'https://www.un-ilibrary.org/content/books/9789210057908s003-en',
  },
  {
    id: 205,
    title: 'Machine Learning Models for Predicting Stock Market Trends',
    author: 'Prof. Alan Turing',
    module: 'Faculty of Computing',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'A follow-up study on applying recurrent neural networks to forecast market movements with higher accuracy.',
    badge: 'Research Paper',
    coverUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=2070&auto=format&fit=crop',
    url: 'https://arxiv.org/pdf/1907.01135.pdf',
  },
  {
    id: 206,
    title: 'Ethical Considerations in AI Governance',
    author: 'Dr. Grace Hopper',
    module: 'Faculty of Computing',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'A framework for establishing ethical guidelines in the development and deployment of artificial intelligence systems.',
    badge: 'Journal Article',
    coverUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=2020&auto=format&fit=crop',
    url: 'https://www.nature.com/articles/s42256-021-00314-5',
  },
  {
    id: 207,
    title: 'Renewable Energy Integration in Urban Grids',
    author: 'Prof. Nikola Tesla',
    module: 'Faculty of Engineering',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'This paper proposes a smart grid architecture for efficiently managing distributed renewable energy sources in cities.',
    badge: 'Conference Paper',
    coverUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?q=80&w=1974&auto=format&fit=crop',
    url: 'https://ieeexplore.ieee.org/document/8950109',
  },
  {
    id: 208,
    title: 'The Role of Storytelling in Modern Marketing',
    author: 'Dr. Maya Angelou',
    module: 'Faculty of Business',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'An exploration of how narrative and storytelling can create powerful brand identities and customer loyalty.',
    badge: 'Journal Article',
    coverUrl: 'https://images.unsplash.com/photo-1455734729978-db1ae4f687fc?q=80&w=1974&auto=format&fit=crop',
    url: 'https://hbr.org/2014/03/the-irresistible-power-of-storytelling-as-a-strategic-business-tool',
  },
  {
    id: 209,
    title: 'Quantum Cryptography: A Practical Implementation',
    author: 'Prof. Alan Turing',
    module: 'Faculty of Computing',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'A breakthrough paper demonstrating a real-world application of quantum key distribution for secure communications.',
    badge: 'Research Paper',
    coverUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?q=80&w=2070&auto=format&fit=crop',
    url: 'https://arxiv.org/pdf/quant-ph/0209114.pdf',
  },
  {
    id: 210,
    title: 'Biomimicry in Architectural Design',
    author: 'Dr. Leonardo da Vinci',
    module: 'Faculty of Engineering',
    category: 'Lecturer Publications',
    type: 'Lecturer Publication',
    availability: 'Online',
    description: 'This publication showcases architectural designs inspired by natural forms and processes to create sustainable and efficient buildings.',
    badge: 'Book Chapter',
    coverUrl: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?q=80&w=2070&auto=format&fit=crop',
    url: 'https://www.archdaily.com/921055/what-is-biomimicry-in-architecture',
  },

  // --- Student Research ---
  {
    id: 301,
    title: 'An Optimized Pathfinding Algorithm for Mobile Robots',
    author: 'Jane Doe (BSc Computing)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'A final year project that introduces a hybrid A* and Dijkstra algorithm for faster pathfinding in complex environments.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?q=80&w=1974&auto=format&fit=crop',
    url: 'https://github.com/topics/pathfinding-algorithm',
  },
  {
    id: 302,
    title: 'Market Analysis of Subscription-Based Services in Sri Lanka',
    author: 'John Smith (BBA Marketing)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'A comprehensive market study on the growth and potential of the subscription economy within the local context.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
    url: 'https://github.com/search?q=market+analysis',
  },
  {
    id: 303,
    title: 'Development of a Low-Cost Water Quality Sensor',
    author: 'A. Perera (BEng Electronics)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'This project details the design and implementation of an affordable IoT-based sensor for real-time water quality monitoring.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?q=80&w=2076&auto=format&fit=crop',
    url: 'https://github.com/search?q=iot+water+quality',
  },
  {
    id: 304,
    title: 'The Effectiveness of Gamification in Primary Education',
    author: 'S. Khan (BSc Psychology)',
    module: 'Research Thesis',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'A study investigating the impact of game-based learning elements on student engagement and knowledge retention.',
    badge: 'Thesis',
    coverUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=2071&auto=format&fit=crop',
    url: 'https://github.com/search?q=gamification+education+research',
  },
  {
    id: 305,
    title: 'Sentiment Analysis of Social Media for Brand Perception',
    author: 'Li Wei (BSc Computing)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'Using natural language processing to analyze public sentiment towards major brands on Twitter and Facebook.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=2072&auto=format&fit=crop',
    url: 'https://github.com/topics/sentiment-analysis',
  },
  {
    id: 306,
    title: 'A Mobile App for Campus Navigation using Augmented Reality',
    author: 'Priya Sharma (BSc Software Engineering)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'This project showcases an AR-powered mobile application to help new students and visitors navigate the campus.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1554321586-92083ba0a115?q=80&w=1998&auto=format&fit=crop',
    url: 'https://github.com/search?q=augmented+reality+navigation',
  },
  {
    id: 307,
    title: 'The Economic Viability of Vertical Farming in Urban Sri Lanka',
    author: 'R. Fernando (BBA Finance)',
    module: 'Research Thesis',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'A feasibility study on implementing vertical farming projects in Colombo to address food security challenges.',
    badge: 'Thesis',
    coverUrl: 'https://images.unsplash.com/photo-1587049352851-d88152d1588a?q=80&w=1974&auto=format&fit=crop',
    url: 'https://github.com/search?q=vertical+farming+research',
  },
  {
    id: 308,
    title: 'Creating a Chatbot for Student Support Services',
    author: 'M. Ali (BSc Computing)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'Development of an AI-powered chatbot to answer frequently asked questions from students regarding administrative and academic matters.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1529420706403-253ab5de5974?q=80&w=2070&auto=format&fit=crop',
    url: 'https://github.com/topics/chatbot',
  },
  {
    id: 309,
    title: 'Analysis of Post-Pandemic Tourism Trends in Sri Lanka',
    author: 'N. Silva (BSc Hospitality Management)',
    module: 'Research Thesis',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'This research identifies key shifts in tourist behavior and preferences in Sri Lanka following the COVID-19 pandemic.',
    badge: 'Thesis',
    coverUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=2070&auto=format&fit=crop',
    url: 'https://github.com/search?q=tourism+research',
  },
  {
    id: 310,
    title: 'A Machine Learning Approach to Detecting Phishing Websites',
    author: 'K. Chen (BSc Cybersecurity)',
    module: 'Final Year Project',
    category: 'Student Research',
    type: 'Student Research',
    availability: 'Online',
    description: 'This project implements a browser extension that uses a machine learning model to detect and block phishing attempts in real-time.',
    badge: 'FYP',
    coverUrl: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?q=80&w=2069&auto=format&fit=crop',
    url: 'https://github.com/topics/phishing-detection',
  },

  // --- Services ---
  {
    id: 401,
    title: 'Book a Study Room',
    author: undefined,
    module: 'Library Facilities',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Reserve a group study room or an individual study carrel for your academic work. Rooms are available for 2-hour slots.',
    badge: 'Booking',
    coverUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/book-room',
  },
  {
    id: 402,
    title: 'Inter-Library Loan Request',
    author: undefined,
    module: 'Resource Sharing',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Need a book or article that our library doesn\'t have? Request it from another library through our inter-library loan service.',
    badge: 'Request',
    coverUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=1974&auto=format&fit=crop',
    route: '/service-details/inter-library-loan',
  },
  {
    id: 403,
    title: 'Ask a Librarian',
    author: undefined,
    module: 'Help & Support',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Get expert help with your research, citations, or any library-related questions. Chat with a librarian online or book a consultation.',
    badge: 'Support',
    coverUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=2190&auto=format&fit=crop',
    route: '/service-details/ask-librarian',
  },
  {
    id: 404,
    title: 'Access Past Exam Papers',
    author: undefined,
    module: 'Academic Resources',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Browse and download past examination papers from all faculties to help you prepare for your upcoming exams.',
    badge: 'Archive',
    coverUrl: 'https://images.unsplash.com/photo-1456735185387-ce2a93a52e6b?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/past-papers',
  },
  {
    id: 405,
    title: 'Printing & Scanning Services',
    author: undefined,
    module: 'Library Facilities',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Use the library\'s multifunction devices to print, photocopy, and scan documents. Top up your print credit online.',
    badge: 'Facilities',
    coverUrl: 'https://images.unsplash.com/photo-1521791136064-7986c28e7481?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/printing',
  },
  {
    id: 406,
    title: 'Research Consultation',
    author: undefined,
    module: 'Help & Support',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Book a one-on-one session with a subject librarian to get in-depth guidance for your thesis or research project.',
    badge: 'Support',
    coverUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/research-consultation',
  },
  {
    id: 407,
    title: 'Digital Literacy Workshops',
    author: undefined,
    module: 'Training & Events',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Sign up for workshops on topics like academic writing, citation management, data analysis tools, and avoiding plagiarism.',
    badge: 'Workshop',
    coverUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/workshops',
  },
  {
    id: 408,
    title: 'Access O\'Reilly for Higher Education',
    author: undefined,
    module: 'eResources',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Get unlimited access to a vast collection of eBooks, videos, and tutorials on technology, business, and more from O\'Reilly.',
    badge: 'Database',
    coverUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/oreilly-access',
  },
  {
    id: 409,
    title: 'Suggest a Purchase',
    author: undefined,
    module: 'Resource Sharing',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Want the library to acquire a book or resource we don\'t currently have? Fill out the suggestion form here.',
    badge: 'Request',
    coverUrl: 'https://images.unsplash.com/photo-1558901357-ca41c4494ff2?q=80&w=1974&auto=format&fit=crop',
    route: '/service-details/suggest-purchase',
  },
  {
    id: 410,
    title: 'Library Feedback Form',
    author: undefined,
    module: 'Help & Support',
    category: 'Services',
    type: 'Service',
    availability: 'Service',
    description: 'Have a suggestion, complaint, or compliment about the library? We value your feedback to help us improve our services.',
    badge: 'Feedback',
    coverUrl: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?q=80&w=2070&auto=format&fit=crop',
    route: '/service-details/feedback',
  },
];
