export const STAFF_DATA = [
  {
    id: '1',
    name: 'Prof. Lakshman Ratnayake',
    title: 'Chancellor | Chairman (SLIIT)',
    image: 'lakshman-ratnayake',
    phone: '0112345678',
    email: 'lakshman.r@sliit.lk',
  },
  {
    id: '2',
    name: 'Prof. Lalith Gamage',
    title: 'Vice Chancellor | MD | CEO (SLIIT)',
    image: 'Prof. Lalith',
    phone: '0112345679',
    email: 'lalith.g@sliit.lk',
  },
  {
    id: '3',
    name: 'Prof. (Miss) Vasanthy Arasaratnam',
    title: 'Vice Chancellor SLIIT NORTHERN UNI',
    image: null,
    phone: '0212220001',
    email: 'vasanthy.a@sliit.nu.lk',
  },
  {
    id: '4',
    name: 'Prof. Nimal Rajapakse',
    title: 'Senior Deputy Vice - Chancellor & Provost(SLIIT)',
    image: 'nimal-rajapakse',
    phone: '0112345680',
    email: 'nimal.r@sliit.lk',
  },
  {
    id: '5',
    name: 'Dr. Gobithas Tharmarajah',
    title: 'CEO|Dean Academic, SLIIT NORTHERN UNI',
    image: null,
    phone: '0212220002',
    email: 'gobithas.t@sliit.nu.lk',
  },
  {
    id: '6',
    name: 'Prof. Rahula Attalage',
    title: 'Pro Vice - Chancellor (Academic - SLIIT)',
    image: 'prof-rahula-attalage',
    phone: '0112345681',
    email: 'rahula.a@sliit.lk',
  },
  {
    id: '7',
    name: 'Prof. Nuwan Kodagoda',
    title: 'Pro Vice Chancellor | Software Engineering | Faculty of Computing',
    image: 'nuwan-kodagoda',
    phone: '0112345682',
    email: 'nuwan.k@sliit.lk',
  },
  {
    id: '8',
    name: 'Prof. Pradeep Abeygunawardhana',
    title: 'Dean | Information Technology | Faculty of Computing.',
    image: null,
    phone: '0112345683',
    email: 'pradeep.a@sliit.lk',
  },
  {
    id: '9',
    name: 'Prof. Suren Peter',
    title: 'Dean - SLIIT Business School (SLIIT)',
    image: 'suren-peter',
    phone: '0112345684',
    email: 'suren.p@sliit.lk',
  },
  {
    id: '10',
    name: 'Dr. Anuradha Karunasena',
    title: 'Associate Dean (Academic - FoC - SLIIT)',
    image: null,
    phone: '0112345685',
    email: 'anuradha.k@sliit.lk',
  },
  {
    id: '11',
    name: 'Dr. Dasuni Nawinna',
    title: 'Associate Dean (Research - FoC- SLIIT)',
    image: null,
    phone: '0112345686',
    email: 'dasuni.n@sliit.lk',
  },
  {
    id: '12',
    name: 'Dr. Mano Weligodapola',
    title: 'Associate Dean (SBS - SLIIT)',
    image: null,
    phone: '0112345687',
    email: 'mano.w@sliit.lk',
  },
  {
    id: '13',
    name: 'Dr. Samantha Rajapaksha',
    title: 'Head | Department of Information Technology (SLIIT)',
    image: null,
    phone: '0112345688',
    email: 'samantha.r@sliit.lk',
  },
  {
    id: '14',
    name: 'Prof. Nisha Jayasuriya',
    title: 'Associate Professor |Head | Department of Business Management',
    image: null,
    phone: '0112345689',
    email: 'nisha.j@sliit.lk',
  },
  {
    id: '15',
    name: 'Prof. B. Nimalathasan',
    title: 'Head | Senior Professor | Department of Business and IT | Head of Administration',
    image: null,
    phone: '0212220003',
    email: 'nimalathasan.b@sliit.nu.lk',
  },
  {
    id: '16',
    name: 'Prof. Koliya Pulasinghe',
    title: 'Senior Professor (SLIIT)',
    image: null,
    phone: '0112345690',
    email: 'koliya.p@sliit.lk',
  },
  {
    id: '17',
    name: 'Dr. Sanvitha Kasthuriarachchi',
    title: 'Senior Lecturer (Higher Grade - SLIIT)',
    image: null,
    phone: '0112345691',
    email: 'sanvitha.k@sliit.lk',
  },
  {
    id: '18',
    name: 'Ms. Uthpala Samarakoon',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345692',
    email: 'uthpala.s@sliit.lk',
  },
  {
    id: '19',
    name: 'Mr. Dhammika De Silva',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345693',
    email: 'dhammika.d@sliit.lk',
  },
  {
    id: '20',
    name: 'Ms. Nilushi Dias',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345694',
    email: 'nilushi.d@sliit.lk',
  },
  {
    id: '21',
    name: 'Ms. Anjalie Gamage',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345695',
    email: 'anjalie.g@sliit.lk',
  },
  {
    id: '22',
    name: 'Ms. Sanjeevi Chandrasiri',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345696',
    email: 'sanjeevi.c@sliit.lk',
  },
  {
    id: '23',
    name: 'Ms. Tharuka Jayathilake',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345697',
    email: 'tharuka.j@sliit.lk',
  },
  {
    id: '24',
    name: 'Ms. Manori Gamage',
    title: 'Senior Lecturer (SLIIT)',
    image: null,
    phone: '0112345698',
    email: 'manori.g@sliit.lk',
  },
  {
    id: '25',
    name: 'Ms. Sankaja Amaraweera',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345699',
    email: 'sankaja.a@sliit.lk',
  },
  {
    id: '26',
    name: 'Ms. Samanthi Siriwardena',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345700',
    email: 'samanthi.s@sliit.lk',
  },
  {
    id: '27',
    name: 'Ms. Sucheru Dissanayake',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345701',
    email: 'sucheru.d@sliit.lk',
  },
  {
    id: '28',
    name: 'Ms. Jenny Krishara',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345702',
    email: 'jenny.k@sliit.lk',
  },
  {
    id: '29',
    name: 'Ms. Keshani Wijesuriya',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345703',
    email: 'keshani.w@sliit.lk',
  },
  {
    id: '30',
    name: 'Ms. Thisuru Dias',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345704',
    email: 'thisuru.d@sliit.lk',
  },
  {
    id: '31',
    name: 'Ms. Ruwanthika Chandrasiri',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345705',
    email: 'ruwanthika.c@sliit.lk',
  },
  {
    id: '32',
    name: 'Ms. Ashani Peiris',
    title: 'Lecturer (SLIIT)',
    image: null,
    phone: '0112345706',
    email: 'ashani.p@sliit.lk',
  },
  {
    id: '33',
    name: 'Ms. Thilini Jayalath',
    title: 'Assistant Lecturer (SLIIT)',
    image: null,
    phone: '0112345707',
    email: 'thilini.j@sliit.lk',
  },
  {
    id: '34',
    name: 'Ms. Colinie Wickramarachchi',
    title: 'Assistant Lecturer (SLIIT)',
    image: null,
    phone: '0112345708',
    email: 'colinie.w@sliit.lk',
  },
  {
    id: '35',
    name: 'Ms. Madhara Prabodini',
    title: 'Assistant Lecturer (SLIIT)',
    image: null,
    phone: '0112345709',
    email: 'madhara.p@sliit.lk',
  },
  {
    id: '36',
    name: 'Dr. S.Mahesan',
    title: 'Senior Lecturer',
    image: null,
    phone: '0212220004',
    email: 'mahesan.s@sliit.nu.lk',
  },
  {
    id: '37',
    name: 'Dr. Dinusha Vatsalan',
    title: 'Senior Lecturer Higher Grade, NORTHERN UNI',
    image: null,
    phone: '0212220005',
    email: 'dinusha.v@sliit.nu.lk',
  },
  {
    id: '38',
    name: 'Mr. A. T. Swampillai',
    title: 'Senior Lecturer',
    image: null,
    phone: '0212220006',
    email: 'swampillai.at@sliit.nu.lk',
  },
  {
    id: '39',
    name: 'Mr. Kanagasabai Thiruthanigesan',
    title: 'Senior Lecturer',
    image: null,
    phone: '0212220007',
    email: 'thiruthanigesan.k@sliit.nu.lk',
  },
  {
    id: '40',
    name: 'Ms. Theevika Sukirthan',
    title: 'Lecturer',
    image: null,
    phone: '0212220008',
    email: 'theevika.s@sliit.nu.lk',
  },
  {
    id: '41',
    name: 'Mr. V. A. M. Ragunathan Sinthujan',
    title: 'Lecturer',
    image: null,
    phone: '0212220009',
    email: 'sinthujan.r@sliit.nu.lk',
  },
  {
    id: '42',
    name: 'Ms. Vishaliney Pirathap',
    title: 'Lecturer',
    image: null,
    phone: '0212220010',
    email: 'vishaliney.p@sliit.nu.lk',
  },
  {
    id: '43',
    name: 'Ms. Sangeetha ArunPrakash',
    title: 'Lecturer',
    image: null,
    phone: '0212220011',
    email: 'sangeetha.a@sliit.nu.lk',
  },
  {
    id: '44',
    name: 'Ms. Inthu Malmaruhan',
    title: 'lecturer',
    image: null,
    phone: '0212220012',
    email: 'inthu.m@sliit.nu.lk',
  },
  {
    id: '45',
    name: 'Ms. Niroji Thayalan',
    title: 'Lecturer',
    image: null,
    phone: '0212220013',
    email: 'niroji.t@sliit.nu.lk',
  },
  {
    id: '46',
    name: 'Ms . Karuneswaran Gowrisha',
    title: 'Assistant Lecturer',
    image: null,
    phone: '0212220014',
    email: 'gowrisha.k@sliit.nu.lk',
  },
  {
    id: '47',
    name: 'Mr. Tharmakulasingam Tharmmendra',
    title: 'Lecturer',
    image: null,
    phone: '0212220015',
    email: 'tharmmendra.t@sliit.nu.lk',
  },
  {
    id: '48',
    name: 'Ms Shanmuganathan Sharmi',
    title: 'Lecturer',
    image: null,
    phone: '0212220016',
    email: 'sharmi.s@sliit.nu.lk',
  },
  {
    id: '49',
    name: 'Ms. Tharsini Amirthalingam',
    title: 'Temporary Assistant Lecturer',
    image: null,
    phone: '0212220017',
    email: 'tharsini.a@sliit.nu.lk',
  },
  {
    id: '50',
    name: 'Ms. Priyanthini Vithushan',
    title: 'Assistant Lecturer',
    image: null,
    phone: '0212220018',
    email: 'priyanthini.v@sliit.nu.lk',
  },
  {
    id: '51',
    name: 'Mr. Benaditamalathas Suthan',
    title: 'Temporary Assistant Lecturer',
    image: null,
    phone: '0212220019',
    email: 'suthan.b@sliit.nu.lk',
  },
  {
    id: '52',
    name: 'Mr. Gokulan Sivakumaran',
    title: 'Assistant Lecturer',
    image: null,
    phone: '0212220020',
    email: 'gokulan.s@sliit.nu.lk',
  },
  {
    id: '53',
    name: 'Mr .Vigneswaran Vithiyasahar',
    title: 'Assistant Lecturer',
    image: null,
    phone: '0212220021',
    email: 'vithiyasahar.v@sliit.nu.lk',
  },
  {
    id: '54',
    name: 'Ms.Thibiga Kanganathan',
    title: 'Academic Instructor',
    image: null,
    phone: '0212220022',
    email: 'thibiga.k@sliit.nu.lk',
  },
  {
    id: '55',
    name: 'Mr.Arumailingam Painthamilan',
    title: 'Academic Instructor - IT',
    image: null,
    phone: '0212220023',
    email: 'painthamilan.a@sliit.nu.lk',
  },
  {
    id: '56',
    name: 'Ms. Princiha Jacob Selvakumar',
    title: 'Academic Instructor',
    image: null,
    phone: '0212220024',
    email: 'princiha.j@sliit.nu.lk',
  },
  {
    id: '57',
    name: 'Mr. Vakeesan Diluxshan',
    title: 'Academic Instructor',
    image: null,
    phone: '0212220025',
    email: 'vakeesan.d@sliit.nu.lk',
  },
  {
    id: '58',
    name: 'Ms. P. Jayapradha',
    title: 'Academic Instructor - IT',
    image: null,
    phone: '0212220026',
    email: 'jayapradha.p@sliit.nu.lk',
  },
  {
    id: '59',
    name: 'Mr. Vinayagamoorthy Balalojanan',
    title: 'Academic Instructor IT',
    image: null,
    phone: '0212220027',
    email: 'balalojanan.v@sliit.nu.lk',
  },
  {
    id: '60',
    name: 'Prof. S.Sivarajasingham',
    title: 'Visiting Lecturer',
    image: null,
    phone: '0212220028',
    email: 'sivarajasingham.s@sliit.nu.lk',
  },
  {
    id: '61',
    name: 'Theivendran Vigneswaran',
    title: 'Visiting Lecturer',
    image: null,
    phone: '0212220029',
    email: 'vigneswaran.t@sliit.nu.lk',
  },
  {
    id: '62',
    name: 'Ms. Lokitha Thussanthan',
    title: 'Library Associate',
    image: null,
    phone: '0212220030',
    email: 'lokitha.t@sliit.nu.lk',
  },
];
